
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xd7*8r4\xcc\xf4,Ab\xad\xbf\xc4\x07\xc1n'
    
_lr_action_items = {'AND':([1,3,4,6,7,9,14,15,16,18,],[-3,-1,-2,-4,10,10,-5,-6,-7,-8,]),'RPAREN':([1,3,4,6,8,9,12,13,14,15,16,17,18,19,],[-3,-1,-2,-4,-9,14,-10,18,-5,-6,-7,-9,-8,-11,]),'SYMBOL':([0,5,8,10,11,17,],[2,2,12,2,2,12,]),'COMMA':([12,],[17,]),'LPAREN':([0,2,5,],[5,8,5,]),'OR':([1,3,4,6,7,9,14,15,16,18,],[-3,-1,-2,-4,11,11,-5,-6,-7,-8,]),'$end':([1,3,4,6,7,14,15,16,18,],[-3,-1,-2,-4,0,-5,-6,-7,-8,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'conjunction':([0,5,],[1,1,]),'function_call':([0,5,10,11,],[3,3,15,16,]),'paren_group':([0,5,],[4,4,]),'disjunction':([0,5,],[6,6,]),'expression':([0,5,],[7,9,]),'query_function_call_args':([8,17,],[13,19,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> function_call','expression',1,'p_expression','/wg/stor5/jbinney/ws/im/src/interactive-manipulation-sandbox/activity_manager/src/activity_manager/query_parser.py',58),
  ('expression -> paren_group','expression',1,'p_expression','/wg/stor5/jbinney/ws/im/src/interactive-manipulation-sandbox/activity_manager/src/activity_manager/query_parser.py',59),
  ('expression -> conjunction','expression',1,'p_expression','/wg/stor5/jbinney/ws/im/src/interactive-manipulation-sandbox/activity_manager/src/activity_manager/query_parser.py',60),
  ('expression -> disjunction','expression',1,'p_expression','/wg/stor5/jbinney/ws/im/src/interactive-manipulation-sandbox/activity_manager/src/activity_manager/query_parser.py',61),
  ('paren_group -> LPAREN expression RPAREN','paren_group',3,'p_paren_group','/wg/stor5/jbinney/ws/im/src/interactive-manipulation-sandbox/activity_manager/src/activity_manager/query_parser.py',70),
  ('conjunction -> expression AND function_call','conjunction',3,'p_conjunction','/wg/stor5/jbinney/ws/im/src/interactive-manipulation-sandbox/activity_manager/src/activity_manager/query_parser.py',76),
  ('disjunction -> expression OR function_call','disjunction',3,'p_disjunction','/wg/stor5/jbinney/ws/im/src/interactive-manipulation-sandbox/activity_manager/src/activity_manager/query_parser.py',82),
  ('function_call -> SYMBOL LPAREN query_function_call_args RPAREN','function_call',4,'p_function_call','/wg/stor5/jbinney/ws/im/src/interactive-manipulation-sandbox/activity_manager/src/activity_manager/query_parser.py',87),
  ('query_function_call_args -> <empty>','query_function_call_args',0,'p_query_function_call_args','/wg/stor5/jbinney/ws/im/src/interactive-manipulation-sandbox/activity_manager/src/activity_manager/query_parser.py',92),
  ('query_function_call_args -> SYMBOL','query_function_call_args',1,'p_query_function_call_args','/wg/stor5/jbinney/ws/im/src/interactive-manipulation-sandbox/activity_manager/src/activity_manager/query_parser.py',93),
  ('query_function_call_args -> SYMBOL COMMA query_function_call_args','query_function_call_args',3,'p_query_function_call_args','/wg/stor5/jbinney/ws/im/src/interactive-manipulation-sandbox/activity_manager/src/activity_manager/query_parser.py',94),
]
