#!/usr/bin/env python
PACKAGE_NAME='mros'
import roslib; roslib.load_manifest(PACKAGE_NAME)
import sys
import rospy

import mros

if __name__ == '__main__':
    rospy.init_node('mros', anonymous=True)
    config_socket_uri = sys.argv[1]
    data_socket_uri = sys.argv[2]    
    mr = mros.MRos(data_socket_uri=data_socket_uri, config_socket_uri=config_socket_uri, is_parent=True)
    mr.run()
