#!/usr/bin/env python
PACKAGE_NAME='mros'
import roslib; roslib.load_manifest(PACKAGE_NAME)
import sys
import rospy

from mros.mros_child import MRosChild

if __name__ == '__main__':
    rospy.init_node('mros', anonymous=True)
    config_socket_uri = sys.argv[1]
    mr = MRosChild(config_socket_uri=config_socket_uri)
    mr.run()
