#!/usr/bin/env python
PACKAGE_NAME='mros'
import roslib; roslib.load_manifest(PACKAGE_NAME)
import sys
import cPickle as pickle
import zmq
import rospy

config_socket_uri = sys.argv[1]
command = sys.argv[2]

context = zmq.Context()
s = context.socket(zmq.REQ)
s.connect(config_socket_uri)

def send_command(cmd):
    s.send(pickle.dumps(cmd))
    res = s.recv()
    return pickle.loads(res)

if command == 'get':
    print send_command(('GET_TOPIC_LIST',))
elif command == 'ad':
    print send_command(('ADVERTISE', ('/my_topic', 'pr2_plugs_msgs/RechargeActionResult', '29d25c66724f23d9bffdb99aca9fbef1')))
else:
    diwenjijasjfoij
