# JSON encoded action to execute
string action

---

# outcome of the state machine. if retval is RETVAL_SUCCESS, this will
# correspond to one of the outcomes in the state machine defined in the goal's json_str.
string outcome

# JSON encoded output values
string outputs

# return value
uint8 retval
uint8 RETVAL_SUCCESS = 0
uint8 RETVAL_PARSE_ERROR = 1
uint8 RETVAL_RUNTIME_ERROR = 2
uint8 RETVAL_OTHER_ERROR = 3

# human readable error string, if something went wrong
string error_string

---
