#!/usr/bin/env python
import roslib; roslib.load_manifest("smach_executer")
import sys
import rospy
import actionlib

from smach_executer.msg import ExecuterInterfaceAction, ExecuterInterfaceGoal

# parse command line args
json_filename = sys.argv[1]
if len(sys.argv) > 2:
    executer_action_topic = sys.argv[2]
else:
    executer_action_topic = '/executer_interface'



# create node and connect to action server
rospy.init_node('executer_caller', anonymous=True)
print '== Connecting to action server'
ac = actionlib.SimpleActionClient(executer_action_topic, ExecuterInterfaceAction)
ac.wait_for_server()

# send goal and wait for result
goal = ExecuterInterfaceGoal()
goal.json_str = open(json_filename).read()
print '== Sending json:'
print goal.json_str
ac.send_goal(goal)
ac.wait_for_result()

result = ac.get_result()
print '== Result:'
print result
