---

- name: update apt
  action: command /usr/bin/apt-get update

- name: install python-software-properties
  action: apt pkg=$item state=present
  with_items:
    - python-software-properties
    - build-essential
    - python-dev
    - python-setuptools

- name: install pip
  action: easy_install name=pip

- name: update easy_install packages
  action: command /usr/bin/easy_install -U distribute

- name: install supervisor
  action: pip name=supervisor state=present

- name: ensure supervisor directory
  action: file dest=/etc/supervisor state=directory

- name: create supervisord config
  action: template src=templates/supervisord.conf dest=/etc/supervisord.conf

- name: create supervisord init script
  action: template src=templates/supervisord.sh dest=/etc/init.d/supervisord mode=0755

- name: start supervisord service
  action: service name=supervisord state=started enabled=yes

