#!/usr/bin/env python
PACKAGE_NAME = 'multi_ros'
import roslib
roslib.load_manifest(PACKAGE_NAME)

from multi_ros.multi_ros_child import MultiRosChild


if __name__ == '__main__':
    child_uri = 'tcp://*'

    # start the multi_ros child in a new process
    child = MultiRosChild(child_uri)
    child.remote_forwarding_loop()
