#!/usr/bin/env python
import roslib
roslib.load_manifest('beginner_tutorials')
import rospy
import sys
from std_msgs.msg import String


def callback(data):
    rospy.loginfo(rospy.get_name() + ": I heard %s" % data.data)


def listener(prefix):
    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber("%s/chatter" % prefix, String, callback)
    rospy.spin()


if __name__ == '__main__':
    if len(sys.argv) > 1:
        prefix = sys.argv[1]
    else:
        prefix = ''
    listener(prefix)
