#!/usr/bin/env python
PACKAGE_NAME = 'multi_ros'
import roslib
roslib.load_manifest(PACKAGE_NAME)
import sys
from multiprocessing import Process
import json

from multi_ros.multi_ros_parent import MultiRosParent
from multi_ros.multi_ros_child import MultiRosChild


def run_child(child_ros_master_uri, child_uri):
    child = MultiRosChild(child_uri, 'multi_ros_child', child_ros_master_uri)
    child.remote_forwarding_loop()


def run_parent(parent_ros_master_uri, child_uri, config_dict):
    parent = MultiRosParent(child_uri, config_dict, 'multi_ros_parent', parent_ros_master_uri)
    parent.remote_forwarding_loop()

if __name__ == '__main__':
    parent_ros_master_uri = sys.argv[1]
    child_ros_master_uri = sys.argv[2]
    config_file = sys.argv[3]

    config_dict = json.loads(open(config_file).read())

    child_uri = 'tcp://127.0.0.1'

    # start the multi_ros child in a new process
    child_process = Process(target=run_child, args=(child_ros_master_uri, child_uri))
    child_process.start()

    import time
    time.sleep(1.0)

    # start the multi_ros parent in the main process
    run_parent(parent_ros_master_uri, child_uri, config_dict)
