#!/usr/bin/env python
PACKAGE_NAME = 'multi_ros'
import roslib
roslib.load_manifest(PACKAGE_NAME)
import sys
import json

from multi_ros.multi_ros_parent import MultiRosParent


if __name__ == '__main__':
    child_name = sys.argv[1]
    config_file = sys.argv[2]

    config_dict = json.loads(open(config_file).read())
    child_uri = 'tcp://%s' % child_name

    # start the multi_ros parent in the main process TODO CLEAN UP THIS BS
    MultiRosParent(child_uri, config_dict)
