#!/usr/bin/env python
import roslib; roslib.load_manifest('mros')
import sys
import rospy
from std_msgs.msg import String

topic = sys.argv[1]
message = sys.argv[2]

rospy.init_node('simple_pub', anonymous=True)

publisher = rospy.Publisher(topic, String)
rospy.sleep(0.5)

msg = String(message)
publisher.publish(msg)
