#!/usr/bin/env python
PACKAGE_NAME = 'multi_ros'
import roslib
roslib.load_manifest(PACKAGE_NAME)
import rospy

from multi_ros.ros_interface import RosInterface

rospy.init_node('ros_interface', anonymous=True)

ri = RosInterface()
ri.update_ros_graph()
d = ri.get_ros_graph()
for t in d:
    print d[t]
