require 'vagrant-ansible'

Vagrant::Config.run do |config|
  config.vm.box     = "layer2-local"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Forward guest port to host port
  config.vm.forward_port 8000, 8001
  config.vm.forward_port 9090, 9091

  # Change IP address for Vagrant host
  config.vm.customize ["modifyvm", :id, "--natnet1", "10.102.100/24"]

  # Share the host folder (3rd argument) with the guest (2nd argument)
  config.vm.share_folder "layer2", "~/layer2", "../../layer2"

  config.vm.provision :ansible do |ansible|
    # Point Vagrant at the location of your playbook you want to run
    ansible.playbook = "webserver.yml"

    # The Vagrant VM will be put in this host group change this should
    # match the host group in your playbook you want to test
    ansible.hosts = "webservers"
  end
end

