#!/usr/bin/env python
import roslib; roslib.load_manifest('activity_manager')
import rospy
from activity_manager.activity_server import ActivityServer

rospy.init_node('activity_manager')

aserv = ActivityServer('activity_manager')
aserv.run()
